categories:
  - id: "cybersecurity"
    name: "网络安全"
    description: "网络安全相关文章和教程"
    subcategories:
      - id: "basics"
        name: "基础入门"
        description: "网络安全基础知识"
      - id: "protocols"
        name: "协议分析"
        description: "网络协议分析"
      - id: "penetration"
        name: "渗透测试"
        description: "渗透测试技术"
      - id: "network-config"
        name: "网络配置"
        description: "网络设备配置"
  
  - id: "ai"
    name: "AI教程"
    description: "人工智能相关教程"
    subcategories:
      - id: "llm"
        name: "大模型"
        description: "大语言模型相关"
      - id: "ai-painting"
        name: "AI绘画"
        description: "AI绘画技术"
      - id: "ai-video"
        name: "AI视频"
        description: "AI视频生成"
  
  - id: "windows"
    name: "Windows教程"
    description: "Windows系统使用教程"
    subcategories:
      - id: "basics"
        name: "基础使用"
        description: "Windows基础操作"
      - id: "advanced"
        name: "高级技巧"
        description: "Windows高级技巧"
  
  - id: "software"
    name: "软件工具"
    description: "软件推荐和使用指南"
    subcategories:
      - id: "productivity"
        name: "效率工具"
        description: "提升效率的工具"
      - id: "development"
        name: "开发工具"
        description: "开发相关工具"
  
  - id: "automation"
    name: "自动化办公"
    description: "自动化办公技巧"
    subcategories:
      - id: "office"
        name: "Office自动化"
        description: "Office套件自动化"
      - id: "workflow"
        name: "工作流自动化"
        description: "工作流程自动化"
  
  - id: "study"
    name: "学习笔记"
    description: "各类学习笔记"
    subcategories:
      - id: "tech"
        name: "技术学习"
        description: "技术相关学习"
      - id: "general"
        name: "通用学习"
        description: "通用知识学习"
  
  - id: "news"
    name: "新闻资讯"
    description: "AI和技术相关新闻"
    subcategories:
      - id: "ai-news"
        name: "AI新闻"
        description: "人工智能相关新闻"
      - id: "tech-news"
        name: "技术新闻"
        description: "技术发展趋势新闻"
      - id: "industry-news"
        name: "行业动态"
        description: "行业发展趋势动态" 