name: 自动获取AI新闻

on:
  schedule:
    - cron: '0 1 * * *'  # 每天UTC时间1点（北京时间9点）运行
  workflow_dispatch:  # 允许手动触发

jobs:
  fetch-and-update:
    runs-on: ubuntu-latest
    
    steps:
      - name: 检出代码
        uses: actions/checkout@v3
      
      - name: 设置Python环境
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name: 安装依赖
        run: |
          python -m pip install --upgrade pip
          pip install requests feedparser
      
      - name: 获取AI新闻
        run: |
          mkdir -p scripts
          python scripts/fetch_ai_news.py
        env:
          TIANXING_API_KEY: ${{ secrets.TIANXING_API_KEY }}
      
      - name: 提交更改
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add src/data/ai/news.ts pushed_news.json
          git diff --quiet && git diff --staged --quiet || (git commit -m "自动更新AI新闻 $(date +'%Y-%m-%d')" && git push)